# 1 Create a numpy array containing the numbers from 1 to 10, and then reshape it to a 2x5 matrix.

In [38]:
# Importing Libraries
import numpy as np
import pandas as pd

In [14]:
# Creating array
arr = np.arange(1, 11)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10]


In [16]:
# Reshaping to 2x5 matrix
reshaped_arr = arr.reshape(2, 5)
print("2x5 Matrix:\n", reshaped_arr)

2x5 Matrix:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


# 2 Create a numpy array containing the numbers from 1 to 20, and then extract the elements between the 5th and 15th index.

In [28]:
# Create array from 1 to 20
arr = np.arange(1, 21)
print (arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [30]:
# Extracting elements 
sliced_arr = arr[5:15]
print("Elements between the 5th and 15th are:", sliced_arr)

Elements between the 5th and 15th are: [ 6  7  8  9 10 11 12 13 14 15]


# 3 Create a Pandas series with the following data: {'apples': 3, 'bananas': 2, 'oranges': 1}. Then, add a new item to the series with the key 'pears' and the value 4

In [44]:
# Create pd series
fruit_series = pd.Series({'apples': 3, 'bananas': 2, 'oranges': 1})

# Printing series
print(fruit_series)

apples     3
bananas    2
oranges    1
dtype: int64


In [42]:
# Add 'pears'
fruit_series['pears'] = 4
print("Updated Series:\n", fruit_series)

Updated Series:
 apples     3
bananas    2
oranges    1
pears      4
dtype: int64


# 4 Create a dataframe with the following columns: name, age, and gender. The dataframe should have 10 rows of data.


In [46]:
# Creating sample data
data = {
    'name': ['Ann', 'Bob', 'Charlie', 'David', 'Alina', 'Frank', 'Grace', 'Mary', 'Ian', 'Jack'],
    'age': [25, 32, 28, 45, 22, 36, 41, 27, 30, 29],
    'gender': ['F', 'M', 'M', 'M', 'F', 'M', 'F', 'F', 'M', 'M']
}

In [48]:
# Creating Dataframe
df = pd.DataFrame(data)
print("DataFrame:\n", df)

DataFrame:
       name  age gender
0      Ann   25      F
1      Bob   32      M
2  Charlie   28      M
3    David   45      M
4    Alina   22      F
5    Frank   36      M
6    Grace   41      F
7     Mary   27      F
8      Ian   30      M
9     Jack   29      M


# 5 Add a new column to the data frame created in question 4, called occupation. The values for this column should be Programmer, Manager, and Analyst, corresponding to the rows in the dataframe.

In [50]:
df['occupation'] = ['Programmer', 'Manager', 'Analyst', 'Manager', 'Programmer', 
                    'Analyst', 'Manager', 'Programmer', 'Analyst', 'Manager']

In [52]:
print("DataFrame with Occupation:\n", df)

DataFrame with Occupation:
       name  age gender  occupation
0      Ann   25      F  Programmer
1      Bob   32      M     Manager
2  Charlie   28      M     Analyst
3    David   45      M     Manager
4    Alina   22      F  Programmer
5    Frank   36      M     Analyst
6    Grace   41      F     Manager
7     Mary   27      F  Programmer
8      Ian   30      M     Analyst
9     Jack   29      M     Manager


# 6 Select the rows of the dataframe where the age is greater than or equal to 30.

In [55]:
# Filter rows where age is 30 and more
age_filtered_df = df[df['age'] >= 30]

print("People with age >= 30:\n", age_filtered_df)

People with age >= 30:
     name  age gender occupation
1    Bob   32      M    Manager
3  David   45      M    Manager
5  Frank   36      M    Analyst
6  Grace   41      F    Manager
8    Ian   30      M    Analyst


# 7 Convert this dataframe to a csv file and read that csv file, finally display the contents

In [57]:
# Save to CSV
df.to_csv("people_data.csv", index=False)

In [59]:
# Read the CSV
df_from_csv = pd.read_csv("people_data.csv")

print("Data from CSV:\n", df_from_csv)

Data from CSV:
       name  age gender  occupation
0      Ann   25      F  Programmer
1      Bob   32      M     Manager
2  Charlie   28      M     Analyst
3    David   45      M     Manager
4    Alina   22      F  Programmer
5    Frank   36      M     Analyst
6    Grace   41      F     Manager
7     Mary   27      F  Programmer
8      Ian   30      M     Analyst
9     Jack   29      M     Manager
